AUDIO_ROOT := $(srctree)/drivers/audio/qcom

include $(AUDIO_ROOT)/config/atollauto.conf
export
INCS    +=  -include $(AUDIO_ROOT)/config/atollautoconf.h

############ UAPI ############
UAPI_DIR :=	uapi
UAPI_INC :=	-I$(AUDIO_ROOT)/include/$(UAPI_DIR)

############ COMMON ############
COMMON_DIR :=	include
COMMON_INC :=	-I$(AUDIO_ROOT)/$(COMMON_DIR)

UAPI_DIR :=	uapi
UAPI_INC :=	-I$(AUDIO_ROOT)/include/$(UAPI_DIR)
COMMON_DIR :=	include
COMMON_INC :=	-I$(AUDIO_ROOT)/$(COMMON_DIR)

############ SoC Modules ############

# for pinctrl LPI driver
# CONFIG_PINCTRL_LPI
PINCTRL_LPI_OBJS += pinctrl-lpi.o

# for new soundwire driver
# CONFIG_SOUNDWIRE_MSTR_CTRL
SWR_CTRL_OBJS += swr-mstr-ctrl.o

# CONFIG_SOUNDWIRE
SWR_OBJS += regmap-swr.o
SWR_OBJS += soundwire.o

# CONFIG_SND_EVENT
SND_EVENT_OBJS += snd_event.o

LINUX_INC +=	-Iinclude/linux

INCS +=		$(COMMON_INC) \
		$(UAPI_INC)

EXTRA_CFLAGS += $(INCS)

CDEFINES +=	-DANI_LITTLE_BYTE_ENDIAN \
		-DANI_LITTLE_BIT_ENDIAN \
		-DDOT11F_LITTLE_ENDIAN_HOST \
		-DANI_COMPILER_TYPE_GCC \
		-DANI_OS_TYPE_ANDROID=6 \
		-DPTT_SOCK_SVC_ENABLE \
		-Wall\
		-Werror\
		-D__linux__

KBUILD_CPPFLAGS += $(CDEFINES)

# Currently, for versions of gcc which support it, the kernel Makefile
# is disabling the maybe-uninitialized warning.  Re-enable it for the
# AUDIO driver.  Note that we must use EXTRA_CFLAGS here so that it
# will override the kernel settings.
ifeq ($(call cc-option-yn, -Wmaybe-uninitialized),y)
EXTRA_CFLAGS += -Wmaybe-uninitialized
endif
#EXTRA_CFLAGS += -Wmissing-prototypes

ifeq ($(call cc-option-yn, -Wheader-guard),y)
EXTRA_CFLAGS += -Wheader-guard
endif

# Module information used by KBuild framework
# CONFIG_PINCTRL_LPI
obj-y += pinctrl_lpi_dlkm.o
pinctrl_lpi_dlkm-y := $(PINCTRL_LPI_OBJS)

# CONFIG_SOUNDWIRE
obj-y += swr_dlkm.o
swr_dlkm-y := $(SWR_OBJS)

# CONFIG_SND_EVENT
obj-y += snd_event_dlkm.o
snd_event_dlkm-y := $(SND_EVENT_OBJS)

# CONFIG_SOUNDWIRE_MSTR_CTRL
obj-y += swr_ctrl_dlkm.o
swr_ctrl_dlkm-y := $(SWR_CTRL_OBJS)
