AUDIO_ROOT := $(srctree)/drivers/audio/qcom

include $(AUDIO_ROOT)/config/atollauto.conf
export
INCS    +=  -include $(AUDIO_ROOT)/config/atollautoconf.h

############ UAPI ############
UAPI_DIR :=	uapi
UAPI_INC :=	-I$(AUDIO_ROOT)/include/$(UAPI_DIR)

############ COMMON ############
COMMON_DIR :=	include
COMMON_INC :=	-I$(AUDIO_ROOT)/$(COMMON_DIR)

UAPI_DIR :=	uapi
UAPI_INC :=	-I$(AUDIO_ROOT)/include/$(UAPI_DIR)
COMMON_DIR :=	include
COMMON_INC :=	-I$(AUDIO_ROOT)/$(COMMON_DIR)

############ ASoC Codecs ############
# CONFIG_WCD9XXX_CODEC_CORE_V2
CORE_OBJS += wcd9xxx-core-init.o
CORE_OBJS += msm-cdc-pinctrl.o
CORE_OBJS += msm-cdc-supply.o

# CONFIG_SND_SOC_WCD9XXX_V2
WCD9XXX_OBJS += wcd-clsh.o
WCD9XXX_OBJS += wcdcal-hwdep.o
WCD9XXX_OBJS += wcd9xxx-soc-init.o
WCD9XXX_OBJS += wcd-dsp-utils.o
WCD9XXX_OBJS += wcd-dsp-mgr.o
WCD9XXX_OBJS += audio-ext-clk-up.o

# CONFIG_SND_SOC_WSA881X
WSA881X_OBJS += wsa881x.o
WSA881X_OBJS += wsa881x-tables.o
WSA881X_OBJS += wsa881x-regmap.o
WSA881X_OBJS += wsa881x-temp-sensor.o

# CONFIG_SND_SOC_MSM_STUB
STUB_OBJS += msm_stub.o

# CONFIG_SND_SOC_WCD_MBHC
MBHC_OBJS += wcd-mbhc-v2.o

# CONFIG_SND_SOC_WCD_MBHC_ADC
MBHC_OBJS += wcd-mbhc-adc.o

# CONFIG_SND_SOC_MSM_HDMI_CODEC_RX
HDMICODEC_OBJS += msm_hdmi_codec_rx.o

# CONFIG_SND_SOC_WCD_IRQ
CORE_OBJS += wcd-irq.o

LINUX_INC +=	-Iinclude/linux

INCS +=		$(COMMON_INC) \
		$(UAPI_INC)

EXTRA_CFLAGS += $(INCS)

CDEFINES +=	-DANI_LITTLE_BYTE_ENDIAN \
		-DANI_LITTLE_BIT_ENDIAN \
		-DDOT11F_LITTLE_ENDIAN_HOST \
		-DANI_COMPILER_TYPE_GCC \
		-DANI_OS_TYPE_ANDROID=6 \
		-DPTT_SOCK_SVC_ENABLE \
		-Wall\
		-Werror\
		-D__linux__

KBUILD_CPPFLAGS += $(CDEFINES)

# Currently, for versions of gcc which support it, the kernel Makefile
# is disabling the maybe-uninitialized warning.  Re-enable it for the
# AUDIO driver.  Note that we must use EXTRA_CFLAGS here so that it
# will override the kernel settings.
ifeq ($(call cc-option-yn, -Wmaybe-uninitialized),y)
EXTRA_CFLAGS += -Wmaybe-uninitialized
endif
#EXTRA_CFLAGS += -Wmissing-prototypes

ifeq ($(call cc-option-yn, -Wheader-guard),y)
EXTRA_CFLAGS += -Wheader-guard
endif

# obj-y	+= wcd934x/
obj-y	+= wcd937x/
obj-y	+= wcd938x/
obj-y	+= bolero/
obj-y	+= tas2562/

# Module information used by KBuild framework
# CONFIG_WCD9XXX_CODEC_CORE_V2
obj-y += wcd_core_dlkm.o
wcd_core_dlkm-y := $(CORE_OBJS)

# CONFIG_SND_SOC_WCD9XXX_V2
obj-y += wcd9xxx_dlkm.o
wcd9xxx_dlkm-y := $(WCD9XXX_OBJS)

# CONFIG_SND_SOC_WSA881X
obj-y += wsa881x_dlkm.o
wsa881x_dlkm-y := $(WSA881X_OBJS)

# CONFIG_SND_SOC_MSM_STUB
obj-y += stub_dlkm.o
stub_dlkm-y := $(STUB_OBJS)

# CONFIG_SND_SOC_WCD_MBHC
obj-y += mbhc_dlkm.o
mbhc_dlkm-y := $(MBHC_OBJS)

# CONFIG_SND_SOC_MSM_HDMI_CODEC_RX
obj-y += hdmi_dlkm.o
hdmi_dlkm-y := $(HDMICODEC_OBJS)
