AUDIO_ROOT := $(srctree)/drivers/audio/qcom

include $(AUDIO_ROOT)/config/atollauto.conf
export
INCS    +=  -include $(AUDIO_ROOT)/config/atollautoconf.h

############ UAPI ############
UAPI_DIR :=	uapi
UAPI_INC :=	-I$(AUDIO_ROOT)/include/$(UAPI_DIR)

############ COMMON ############
COMMON_DIR :=	include
COMMON_INC :=	-I$(AUDIO_ROOT)/$(COMMON_DIR)

UAPI_DIR :=	uapi
UAPI_INC :=	-I$(AUDIO_ROOT)/include/$(UAPI_DIR)
COMMON_DIR :=	include
COMMON_INC :=	-I$(AUDIO_ROOT)/$(COMMON_DIR)

############ BOLERO ############

# for BOLERO Codec
# CONFIG_SND_SOC_BOLERO
BOLERO_OBJS += bolero-cdc.o
BOLERO_OBJS += bolero-cdc-utils.o
BOLERO_OBJS += bolero-cdc-regmap.o
BOLERO_OBJS += bolero-cdc-tables.o
BOLERO_OBJS += bolero-clk-rsc.o

# CONFIG_WSA_MACRO
WSA_OBJS += wsa-macro.o

# CONFIG_VA_MACRO
VA_OBJS += va-macro.o

# CONFIG_TX_MACRO
TX_OBJS += tx-macro.o

# CONFIG_RX_MACRO
RX_OBJS += rx-macro.o

LINUX_INC +=	-Iinclude/linux

INCS +=		$(COMMON_INC) \
		$(UAPI_INC)

EXTRA_CFLAGS += $(INCS)

CDEFINES +=	-DANI_LITTLE_BYTE_ENDIAN \
		-DANI_LITTLE_BIT_ENDIAN \
		-DDOT11F_LITTLE_ENDIAN_HOST \
		-DANI_COMPILER_TYPE_GCC \
		-DANI_OS_TYPE_ANDROID=6 \
		-DPTT_SOCK_SVC_ENABLE \
		-Wall\
		-Werror\
		-D__linux__

KBUILD_CPPFLAGS += $(CDEFINES)

# Currently, for versions of gcc which support it, the kernel Makefile
# is disabling the maybe-uninitialized warning.  Re-enable it for the
# AUDIO driver.  Note that we must use EXTRA_CFLAGS here so that it
# will override the kernel settings.
ifeq ($(call cc-option-yn, -Wmaybe-uninitialized),y)
EXTRA_CFLAGS += -Wmaybe-uninitialized
endif
#EXTRA_CFLAGS += -Wmissing-prototypes

ifeq ($(call cc-option-yn, -Wheader-guard),y)
EXTRA_CFLAGS += -Wheader-guard
endif

# Module information used by KBuild framework
# CONFIG_SND_SOC_BOLERO
obj-y += bolero_cdc_dlkm.o
bolero_cdc_dlkm-y := $(BOLERO_OBJS)

# CONFIG_WSA_MACRO
obj-y += wsa_macro_dlkm.o
wsa_macro_dlkm-y := $(WSA_OBJS)

# CONFIG_VA_MACRO
obj-y += va_macro_dlkm.o
va_macro_dlkm-y := $(VA_OBJS)

# CONFIG_TX_MACRO
obj-y += tx_macro_dlkm.o
tx_macro_dlkm-y := $(TX_OBJS)

# CONFIG_RX_MACRO
obj-y += rx_macro_dlkm.o
rx_macro_dlkm-y := $(RX_OBJS)
